---

- hosts: web_server
  become: true
  tasks:

  - name: install apache and php packages
    tags: apache,php,debian
    package:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

- hosts: db_server
  become: true
  tasks:

  - name: install mariadb and mysql packages
    tags: db,mariadb,mysql,archlinux
    package:
      name:
        - mariadb
        - mysql
      state: latest
      update_cache: yes
    when: ansible_distribution == "Archlinux"

  - name: Enable and start databse
    tags: db,mariadb
    systemd:
      name: mariadb
      enabled: yes
      state: started
    when: ansible_distribution == "Archlinux"
